### ISSUE TITLE
Document Level ACL

### ISSUE THREAD

**Issue by deefactorial** [thaliproject/thali-acl#2]
Will Thali Acl support document level ACL similar to the way couchbase sync gateway does with it's sync function ? 

http://developer.couchbase.com/mobile/develop/guides/sync-gateway/sync-function-api-guide/validation/index.html

**Comment by mpodwysocki** [comment]
@deefactorial yes, that is the intention with this project to protect all endpoints, especially with our express-pouchdb interface to it.

**Comment by deefactorial** [comment]
Excellent
